# database/schemas/_snowflake_overrides.py
"""Centralized registry of per-table Snowflake column type overrides.

Used by ``BackupSchemaRegistry.expected_snowflake_types`` (in
database/backup/schema_registry.py) to suppress false-positive type
mismatches when sqlglot's generic SQLite→Snowflake transpiler produces
a type that differs from the desired Snowflake column type.

Why this matters:
    SnowflakeSchemaManager.reconcile_types() compares the actual Snowflake
    column type against the expected type derived from the SQLite DDL.
    If they differ, the entire table is dropped, recreated, and repopulated
    from local SQLite on every startup. For tables with many rows (e.g.
    scraped_articles_vec_backup with ~586 rows of 1024-dim embeddings),
    this is a significant waste of bandwidth and Snowflake compute.

    The generic transpiler (sqlite_type_to_snowflake in
    database/management/schema_introspector.py) maps SQLite types as:
        INTEGER → NUMBER
        TEXT    → VARCHAR
        BLOB    → BINARY
        REAL    → FLOAT
        (other) → NUMBER

    This is correct for most columns, but some columns need a different
    Snowflake type. For example:
        - scraped_articles_vec_backup.embedding is BLOB in SQLite but
          VECTOR(FLOAT, 1024) in Snowflake. Without an override, the
          reconciler sees BINARY (expected) vs VECTOR (actual) and
          rebuilds the table on every startup.
        - sf_quarterly_facts.is_total is INTEGER in SQLite but BOOLEAN
          in Snowflake (for clearer semantics in Snowflake queries).
          Without an override, the reconciler sees NUMBER vs BOOLEAN
          and rebuilds the table on every startup.

Override format:
    SNOWFLAKE_COLUMN_OVERRIDES: dict[str, dict[str, str]] = {
        "<table_name>": {
            "<column_name_lower>": "<snowflake_type>",
        },
    }

    The column name key is matched case-insensitively (callers should
    lowercase the column name before lookup). The snowflake_type value
    is used verbatim in DDL generation and type comparison.

Reference:
    - Snowflake VECTOR type: https://docs.snowflake.com/en/sql-reference/data-types-vector
    - Snowflake BOOLEAN type: https://docs.snowflake.com/en/sql-reference/data-types-logical
"""
from __future__ import annotations

# Mapping: {table_name: {column_name_lower: snowflake_type}}
#
# When adding a new override, also verify that:
#   1. The Snowflake DDL generated by BackupSchemaRegistry.get_snowflake_ddl()
#      produces the same type (otherwise the table will be created with one
#      type but the reconciler will expect another).
#   2. The override value matches the actual column type in Snowflake
#      (query INFORMATION_SCHEMA.COLUMNS to verify).
SNOWFLAKE_COLUMN_OVERRIDES: dict[str, dict[str, str]] = {
    "sf_quarterly_facts": {
        # SQLite INTEGER → generic transpiler maps to NUMBER, but the
        # Snowflake table uses BOOLEAN for clearer query semantics.
        "is_total": "BOOLEAN",
    },
    "scraped_articles_vec_backup": {
        # SQLite BLOB → generic transpiler maps to BINARY, but the
        # Snowflake table uses VECTOR(FLOAT, 1024) for native vector
        # operations. Without this override, reconcile_types flags
        # BINARY vs VECTOR as a mismatch and rebuilds the table on
        # every startup, re-pushing ~586 rows of embeddings each time.
        "embedding": "VECTOR(FLOAT, 1024)",
    },
}
